### PR TITLE
Add support for Haifa tree felling permits (issue #597)

### PR DESCRIPTION
**Pull request by tomers**

### CODE REVIEW

**Comment by GalGend** [comment]
Hi @tomers is this ready for review?

**Comment by tomers** [comment]
> Hi @tomers is this ready for review?

Sure it is!
This code assumed the Excel file exist in a given URL. I will separately add the conjob task which creates the Excel file.

**Comment by GalGend** [comment]
That's great! Is the file there on the address? Can you please attach here an example file?

**Comment by tomers** [comment]
Yes, the file is here:
https://haifa-tree-felling-permits.s3.eu-central-1.amazonaws.com/rptPirsum.xlsx

This is a temporary bucket. We will need to establish our own.

**Pull request closed without merging**
